### PR TITLE
[video filter] use copy instead of scale when streamCount is 1

### PR DESCRIPTION
**Pull request by aasadalive**

### CODE REVIEW

**Comment by mekya** [comment]
Thank you @aasadalive for your contribution. You're great.  

I would like to add you on linkedin. However, I cannot find your profile. Please add me if it's ok for you
https://www.linkedin.com/in/ahmetoguzmermerkaya/

**Review by mekya — APPROVED** [review]

**Comment by aasadalive** [comment]
>  Please add me if it's ok for you https://www.linkedin.com/in/ahmetoguzmermerkaya/

Done

**Comment by mekya** [comment]
Thank you. I'll accept it when I see a new connection request. It's not listed yet for some reason :S

**Comment by aasadalive** [comment]
Strange, anyway here is mine:
- https://linkedin.com/in/abdellatif-a.923411a7
- https://github.com/aitboudad

**Comment by mekya** [comment]
Thank you.

Added.

**Pull request merged**
